//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.Data.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er ging iets mis!.
        /// </summary>
        internal static string BadRequestErrorMessage {
            get {
                return ResourceManager.GetString("BadRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nieuwe cursus(sen) toegevoegd, {1} nieuwe instantie(s) toegevoegd..
        /// </summary>
        internal static string CursussenToegevoegd {
            get {
                return ResourceManager.GetString("CursussenToegevoegd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} cursus(sen) dubbel, niet toegevoegd..
        /// </summary>
        internal static string DuplicateCursussen {
            get {
                return ResourceManager.GetString("DuplicateCursussen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} cursusinstantie(s) dubbel, niet toegevoegd..
        /// </summary>
        internal static string DuplicateInstanties {
            get {
                return ResourceManager.GetString("DuplicateInstanties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel {0} is niet in het juiste formaat, regel {0} moet Cursuscode zijn met formaat: &apos;Cursuscode: &lt;code&gt;&apos;.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel {0} is niet in het juiste formaat, regel {0} moet Cursusduur zijn met formaat: &apos;Duur: # dagen&apos;.
        /// </summary>
        internal static string InvalidDuur {
            get {
                return ResourceManager.GetString("InvalidDuur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel {0} is niet in het juiste formaat, regel {0} moet Startdatum zijn met formaat: &apos;Startdatum: 01/01/2020&apos;.
        /// </summary>
        internal static string InvalidStartdatum {
            get {
                return ResourceManager.GetString("InvalidStartdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel {0} is niet in het juiste formaat, regel {0} moet Titel zijn met formaat: &apos;Titel: &lt;titel&gt;&apos;.
        /// </summary>
        internal static string InvalidTitel {
            get {
                return ResourceManager.GetString("InvalidTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel {0} is niet in het juiste formaat: Regel {0} moet een witregel zijn.
        /// </summary>
        internal static string ShouldBeEmptyLine {
            get {
                return ResourceManager.GetString("ShouldBeEmptyLine", resourceCulture);
            }
        }
    }
}
